apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-eventautomation-flink-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-eventautomation-flink-1.1.9
  publisher: IBM
  image: icr.io/cpopen/ibm-eventautomation-flink-operator-catalog@sha256:4031d9aa19cd5676ca08be370570e45f68979fa54f36b2c762e983baf08a4dce
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s