apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-eventprocessing-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-eventprocessing-1.1.9
  publisher: IBM
  image: icr.io/cpopen/ibm-eventprocessing-operator-catalog@sha256:2442caf0b77974b2900fee436998df2a686359980c881ff2e6b68a1b66aeb2dc
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s