apiVersion: integration.ibm.com/v1beta1
kind: IntegrationAssembly
metadata:
  name: ia-demo
  namespace: tools
spec:
  license:
    accept: true
    license: L-VTPK-22YZPK
    use: CloudPakForIntegrationNonProduction
  version: 2023.4.1
  managedInstances:
    list: []
  managedIntegrations:
    list:
      - kind: API
        metadata:
          name: jgr-esaapi-ia
        spec:
          definition:
            integrationRuntime: 
              name: jgr-esapi-scram
            security:
              type: ClientID
          share:
            apim:
              credentialsSecret: apim-credentials
              providerOrg: cp4i-demo-org
      - kind: IntegrationRuntime
        metadata:
          name: jgr-esapi-scram
        spec:
          license:
            accept: true
            license: L-QECF-MBXVLU
            use: CloudPakForIntegrationNonProduction
          version: '12.0'
          barURL:
            - >-
              https://github.com/gomezrjo/cp4idemo/raw/main/barfiles/jgr-cp4i-esapi-scram.bar
          configurations:
            - github-barauth
            - ace-es-demo-scram-policy
            - ace-es-demo-scram-secid
            - es-cert.jks
  storage:
    readWriteOnce:
      class: ${OCP_BLOCK_STORAGE}
