apiVersion: integration.ibm.com/v1beta1
kind: AssetRepository
metadata:
  labels:
    backup.integration.ibm.com/component: assetrepository
  name: asset-repo-ai
spec:
  designerAIFeatures:
    enabled: true
  license:
    accept: true
    license: L-VTPK-22YZPK
  replicas: 1
  singleReplicaOnly: true
  storage:
    assetDataVolume:
      class: ${OCP_BLOCK_STORAGE}
      size: 100Mi
    couchVolume:
      class: ${OCP_BLOCK_STORAGE}
  version: 2023.4.1
