apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  name: qmgr-demo
  labels:
    assembly.integration.ibm.com/tools.jgr-demo: 'true'
spec:
  annotations:
    productMetric: FREE
  license:
    accept: true
    license: L-VTPK-22YZPK
    use: NonProduction
  queueManager:
    name: QMGRDEMO
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      queueManager:
        type: persistent-claim
      defaultClass: ${OCP_BLOCK_STORAGE}
    availability:
      type: SingleInstance
    mqsc:
      - configMap:
          name: mq-demo-mqsc
          items:
            - mq-demo-resources.mqsc
  version: 9.3.5.1-r2
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
