apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  annotations:
    com.ibm.mq/write-defaults-spec: 'false'
  name: qmgr-demo
  namespace: tools
  labels:
    assembly.integration.ibm.com/tools.jgr-demo: 'true'
spec:
  annotations:
    productMetric: FREE
  license:
    accept: true
    license: L-JTPV-KYG8TF
    use: NonProduction
  pki:
    keys:
      - name: default
        secret:
          secretName: mq-demo-tls-secret
          items: 
          - tls.key
          - tls.crt
  queueManager:
    name: QMGRDEMO
    resources:
      limits:
        cpu: 500m
      requests:
        cpu: 500m
    storage:
      queueManager:
        type: persistent-claim
      defaultClass: ${OCP_BLOCK_STORAGE}
    availability:
      type: SingleInstance
    mqsc:
      - configMap:
          name: mq-demo-mqsc
          items:
            - mq-demo-resources.mqsc
  version: 9.4.0.0-r1
  web:
    console:
      authentication:
        provider: integration-keycloak
      authorization:
        provider: integration-keycloak
    enabled: true
