apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: es-admin
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - operations:
          - Alter
          - DescribeConfigs
        resource:
          type: cluster
      - operations:
          - Create
          - Read
          - Write
          - Delete
          - DescribeConfigs
          - Alter
          - AlterConfigs
        resource:
          name: '*'
          patternType: literal
          type: topic
      - operations:
          - Alter
          - Read
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - operations:
          - Read
          - Delete
        resource:
          name: '*'
          patternType: literal
          type: group
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: ace-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operations:
          - Read
          - Write
          - Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operations:
          - Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operations:
          - Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: designer-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operations:
          - Read
          - Write
          - Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operations:
          - Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operations:
          - Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: kafka-connect-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operations:
          - Read
          - Write
          - Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operations:
          - Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operations:
          - Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: kafka-bridge-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operations:
          - Read
          - Write
          - Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operations:
          - Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operations:
          - Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: eem-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operations:
          - Read
          - Write
          - Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operations:
          - Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operations:
          - Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: ep-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operations:
          - Read
          - Write
          - Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operations:
          - Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operations:
          - Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple
---
apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  labels:
    app.kubernetes.io/instance: es-demo
    eventstreams.ibm.com/cluster: es-demo
  name: apic-analytics-offload-user
  namespace: tools
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operations:
          - Read
          - Write
          - Create
        resource:
          name: '*'
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Alter
        resource:
          name: __schema_
          patternType: prefix
          type: topic
      - host: '*'
        operations:
          - Read
        resource:
          name: '*'
          patternType: literal
          type: group
      - host: '*'
        operations:
          - Write
        resource:
          name: '*'
          patternType: literal
          type: transactionalId
    type: simple