apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-3.1.3
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:b6cf3b792a6b15165d1a80f2fbffc0eb59f31bcd571de42a03cfa104510ec917
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s