apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-eventprocessing-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-eventprocessing-1.1.7
  publisher: IBM
  image: icr.io/cpopen/ibm-eventprocessing-operator-catalog@sha256:a08b3307ff18586d60c3ba76fc1e10b1ed40a160b742046c18b746cbc4f1a1d3
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s